apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64.exe convert --out tmp/k8s/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: celery-worker
  name: celery-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: celery-worker
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose-windows-amd64.exe convert --out tmp/k8s/
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: celery-worker
    spec:
      containers:
        - args:
            - celery
            - -A
            - src.tasks
            - worker
            - --loglevel=info
          env:
            - name: CELERY_BROKER_URL
              value: amqp://myuser:mypassword@rabbitmq/myvhost
            - name: PYTHONPATH
              value: /app
          image: celery-worker
          name: celery-worker
          ports:
            - containerPort: 5672
              protocol: TCP
          volumeMounts:
            - mountPath: /app/data
              name: celery-worker-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: celery-worker-cm0
          name: celery-worker-cm0
